# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 luvsmallfamily.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase # 替換為你的資料庫資訊
      - SECRET_KEY=your_secret_key # Django SECRET_KEY
      - DEBUG=True # 生產環境務必設定為 False
    env_file:
      - .env # 也可以使用 .env 檔案來管理環境變數

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

volumes:
  mysql_data: